### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/candy48#1]
- [x] Up and down movement
- [x] Matching of three same color shapes should 
  - [ ] Fade out using jQuery
  - [x] Increase score by 100
- [x] Have levels: Start with 2 colors, increment by one color per level
- [ ] In upper levels, make stationary blocks if more difficulty is needed
- [ ] Make prettier! 
  - [x] Shape images
  - [ ] Background that changes with each level
