### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/candy48#19]
- [ ] Use alien animals :alien: :cow:
- [ ] Rename to Space Zoo
- [ ] Make mobile version
- [ ] New story
